### ISSUE TITLE
Setup hangs

### ISSUE THREAD

**Issue by VibrantSausage** [wikitops/ansible_tableau#11]
Hi whilst trying to setup on OSX Mojave (10.14.5) with a fresh install of VirtualBox 6.0.8

I get this output and then it hangs (in ruby it seems):

```
    tableau01: Preparing to unpack .../open-vm-tools_2%3a10.3.10-1~ubuntu0.18.04.1_amd64.deb ...
    tableau01: Unpacking open-vm-tools (2:10.3.10-1~ubuntu0.18.04.1) over (2:10.3.5-7~ubuntu0.18.04.1) ...
    tableau01: Processing triggers for ureadahead (0.100.0-21) ...
    tableau01: Processing triggers for libc-bin (2.27-3ubuntu1) ...
    tableau01: Setting up libssl1.1:amd64 (1.1.1-1ubuntu2.1~18.04.2) ...
    tableau01: Checking for services that may need to be restarted...
    tableau01: done.
    tableau01: Checking for services that may need to be restarted...
    tableau01: done.
    tableau01: Checking init scripts...
    tableau01:
    tableau01: Setting up libgcc1:amd64 (1:8.3.0-6ubuntu1~18.04.1) ...
    tableau01: (Reading database ...
(Reading database ... 55%atabase ... 5%
    tableau01: (Reading database ... 60%
    tableau01: (Reading database ... 65%
    tableau01: (Reading database ... 70%
    tableau01: (Reading database ... 75%
    tableau01: (Reading database ... 80%
    tableau01: (Reading database ... 85%
    tableau01: (Reading database ... 90%
    tableau01: (Reading database ... 95%
(Reading database ... 59800 files and directories currently installed.)
    tableau01: Preparing to unpack .../libssl1.1_1.1.1-1ubuntu2.1~18.04.2_amd64.deb ...
    tableau01: Unpacking libssl1.1:amd64 (1.1.1-1ubuntu2.1~18.04.2) over (1.1.1-1ubuntu2.1~18.04.1) ...
    tableau01: Preparing to unpack .../openssl_1.1.1-1ubuntu2.1~18.04.2_amd64.deb ...
    tableau01: Unpacking openssl (1.1.1-1ubuntu2.1~18.04.2) over (1.1.1-1ubuntu2.1~18.04.1) ...
    tableau01: Processing triggers for libc-bin (2.27-3ubuntu1) ...
    tableau01: Setting up libssl1.1:amd64 (1.1.1-1ubuntu2.1~18.04.2) ...
    tableau01: Checking for services that may need to be restarted...
    tableau01: done.
    tableau01: Checking for services that may need to be restarted...
    tableau01: done.
    tableau01: Checking init scripts...
    tableau01:
```
